// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  news_block_first: dynamic(() => import("./NewsBlockFirst")),
  news_block_second: dynamic(() => import("./NewsBlockSecond")),
};
