import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Header from "@/components/Header";
import MainContainer from "@/components/MainContainer";
import "./globals.css";

const DMSans = DM_Sans({
	variable: "--font-dm-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "La Baule TV",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			<body className={DMSans.className}>
				<Header />
				<MainContainer>{children}</MainContainer>
			</body>
		</html>
	);
}
