import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import MainContainer from "@/app/components/MainContainer";
import ResponsiveHeader from "./components/ResponsiveHeader";
import Footer from "./components/Footer";
import "./globals.css";

const DMSans = DM_Sans({
	variable: "--font-dm-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "La Baule TV",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			<body className={DMSans.className}>
				<ResponsiveHeader />
				<MainContainer>{children}</MainContainer>
				<Footer />
			</body>
		</html>
	);
}
